trigger:
  tags:
    include:
    - '*'
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useExternalRegistry
    publishEndpoint: 'NPM'
