name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Get version
        run: |
          echo "VERSION=$(cat package.json | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["version"])')" >> $GITHUB_ENV
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.AUSTRAKKA_ACTIONS_PAT }}
          custom_tag: ${{ env.VERSION }}
          tag_prefix: ''
